---
title: "cameron_visualization"
author: "Cameron Stivers"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(plotly)
library(readr)
```


```{r}
region_dat <- read.csv(here("431Data/salaries-by-region.csv"))
```

```{r}
region_dat_clean <- region_dat %>%
  select(c(School.Name, Region, Starting.Median.Salary, Mid.Career.Median.Salary)) %>%
  mutate(Starting.Median.Salary = parse_number(Starting.Median.Salary)) %>%
  mutate(Mid.Career.Median.Salary = parse_number(Mid.Career.Median.Salary))
```

```{r}
region_dat_clean %>%
  ggplot(aes(x = Starting.Median.Salary, y = Region, fill = Region)) +
  geom_boxplot() +
  geom_jitter(color = "black", size = 0.7, alpha = 0.5) +
  xlab("Starting Median Salary") +
  theme_classic()
```

```{r}
region_dat_clean %>%
  plot_ly(x = ~Starting.Median.Salary, color = ~Region, type = "box", 
          boxpoints = "all", jitter = 0.7, alpha = 0.5, pointpos = 0,
          text = ~School.Name) 
```

```{r}
region_dat_clean %>%
  plot_ly(x = ~Mid.Career.Median.Salary, color = ~Region, type = "box", 
          boxpoints = "all", jitter = 0.7, alpha = 0.5, pointpos = 0,
          text = ~School.Name) 
```

